[#127] Made dynamic condition for no managed files step.
drevops/behat-steps pull request #180
Opened 2024-01-25 10:02 UTC by tannguyen04

closes #127

2024-02-02 13:24 UTC, AlexSkrypnyk requested changes
@tannguyen04 
Please see my inline comments.

2024-02-02 13:24 UTC, AlexSkrypnyk commented on src/FileTrait.php
> +   * Example: filename, uri, status, uid and more see Drupal\file\Entity\File.
```
Example: filename, uri, status, uid and more.

@see Drupal\file\Entity\File
```

2024-02-02 13:24 UTC, AlexSkrypnyk commented on src/FileTrait.php
> +   * | fieldName     |
please revert this change and add a second `@code/@endcode` with another example of using a different field name - `path`.

2024-02-02 13:24 UTC, AlexSkrypnyk commented on src/FileTrait.php
> +    $fieldValues = $nodesTable->getColumn(0);
do not use camelCase - for variables - please use snake_case

2024-02-02 13:24 UTC, AlexSkrypnyk commented on tests/behat/features/file.feature
> -      | path                 |
please add another test to show that a different field name also works.

2024-02-03 09:52 UTC, tannguyen04 commented
Hi @AlexSkrypnyk 
I have updated as your request.

2024-02-05 01:49 UTC, AlexSkrypnyk approved these changes

2024-02-05 01:50 UTC, merged